baseURL = "https://moorts.github.io/"
languageCode = "en-us"
title = "Moorts' Blog"
theme = "hyde"
# pygmentsUseClasses=true
math = true

[params]
    author = "Moritz Gutfleisch"
    description = "Hello there"

[menu]

#    [[menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "
